// Landing page components barrel export
export { default as Navbar } from './layout/Navbar'
export { default as Footer } from './layout/Footer'
export { default as HeroSection } from './sections/HeroSection'
export { default as StatsSection } from './sections/StatsSection'
export { default as ValueProposition } from './sections/ValueProposition'
export { default as FeaturesSection } from './sections/FeaturesSection'
export { default as CostComparisonSection } from './sections/CostComparisonSection'
export { default as TestimonialsSection } from './sections/TestimonialsSection'
export { default as PricingSection } from './sections/PricingSection'
export { default as CTASection } from './sections/CTASection'
