// Landing page components barrel export
export { default as Navbar } from './Navbar'
export { default as HeroSection } from './HeroSection'
export { default as StatsSection } from './StatsSection'
export { default as ValueProposition } from './ValueProposition'
export { default as FeaturesSection } from './FeaturesSection'
export { default as CostComparisonSection } from './CostComparisonSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as PricingSection } from './PricingSection'
export { default as CTASection } from './CTASection'
export { default as Footer } from './Footer'
